### ISSUE TITLE
We cannot create more than 10 users at once

### ISSUE THREAD

**Issue by hei-teacher** [hei-school/hei-admin-api#37]
- This is because we cannot send more than 10 UserUpserted events at once
- In such a failure, database entries should be rolled back ==> creation should be @Transactional!

Nb of users that can be created in batch is bounded by the number of events we can send at once. This is because send multiple batch of events and that some of them fail, we have now way of taking back all the other events that were successfully sent. **As EventBridge.PutEvents can only handle 10 events at once, we must limit user creation to 10 users**
https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutEvents.html

**Comment by hei-ryan** [comment]
This exception is now treated by UserController and tested here : https://github.com/hei-school/hei-admin-api/pull/42
