### ISSUE TITLE
Document the execution of integration tests

### ISSUE THREAD

**Issue by hei-teacher** [hei-school/hei-admin-api#9]
In particular, document how to get Cognito tokens?

Related issue: https://github.com/hei-school/hei-admin-api/issues/10

**Comment by hei-ryan** [comment]
https://github.com/hei-school/hei-admin-api/wiki/Checkstyle

**Comment by hei-ryan** [comment]
https://github.com/hei-school/hei-admin-api/wiki/Integration-Test
